// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWLhywAewxdudOAD_nVGj62kk80zHtIzQ',
    appId: '1:1070137994645:web:4e313b7b325252fa6f9a9c',
    messagingSenderId: '1070137994645',
    projectId: 'kissanconnect-c0c27',
    authDomain: 'kissanconnect-c0c27.firebaseapp.com',
    storageBucket: 'kissanconnect-c0c27.appspot.com',
    measurementId: 'G-5927XCFB3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_kCHtGqXuQFDtNuaQZS1Q8Soh9Z7nv7Q',
    appId: '1:1070137994645:android:9e8f122eeeafbed86f9a9c',
    messagingSenderId: '1070137994645',
    projectId: 'kissanconnect-c0c27',
    storageBucket: 'kissanconnect-c0c27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeBrKcpdoD_UtzhQ0CzynOj8dmHIjoA7k',
    appId: '1:1070137994645:ios:a8a21cd23cc647836f9a9c',
    messagingSenderId: '1070137994645',
    projectId: 'kissanconnect-c0c27',
    storageBucket: 'kissanconnect-c0c27.appspot.com',
    iosBundleId: 'com.example.kissanconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeBrKcpdoD_UtzhQ0CzynOj8dmHIjoA7k',
    appId: '1:1070137994645:ios:a8a21cd23cc647836f9a9c',
    messagingSenderId: '1070137994645',
    projectId: 'kissanconnect-c0c27',
    storageBucket: 'kissanconnect-c0c27.appspot.com',
    iosBundleId: 'com.example.kissanconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWLhywAewxdudOAD_nVGj62kk80zHtIzQ',
    appId: '1:1070137994645:web:46facd64755410396f9a9c',
    messagingSenderId: '1070137994645',
    projectId: 'kissanconnect-c0c27',
    authDomain: 'kissanconnect-c0c27.firebaseapp.com',
    storageBucket: 'kissanconnect-c0c27.appspot.com',
    measurementId: 'G-BHV1FF3B8X',
  );
}
